version: '3'
services:
  web:
    container_name: web_gossip
    build: . # 使用myproject目录下的Dockerfile
    volumes:
      - .:/home/Gossip # 挂载项目代码
    restart: always
    tty: true
    stdin_open: true
    ports:
      - "443:8443"
